[2025-05-12T21:11:22.290+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-12T21:11:22.312+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T20:00:10.933027+00:00 [queued]>
[2025-05-12T21:11:22.316+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T20:00:10.933027+00:00 [queued]>
[2025-05-12T21:11:22.316+0100] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2025-05-12T21:11:22.323+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-05-12 20:00:10.933027+00:00
[2025-05-12T21:11:22.332+0100] {logging_mixin.py:188} WARNING - /Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4520) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-12T21:11:22.332+0100] {standard_task_runner.py:64} INFO - Started process 4531 to run task
[2025-05-12T21:11:22.337+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_daily_pipeline', 'dbt_run', 'manual__2025-05-12T20:00:10.933027+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/var/folders/x8/bvc5rcpd5t12mfz1khbckdsm0000gn/T/tmpr8tnc_xe']
[2025-05-12T21:11:22.342+0100] {standard_task_runner.py:91} INFO - Job 28: Subtask dbt_run
[2025-05-12T21:11:22.400+0100] {task_command.py:426} INFO - Running <TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T20:00:10.933027+00:00 [running]> on host macbookair.lan
[2025-05-12T21:11:22.739+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='youtube_daily_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T20:00:10.933027+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T20:00:10.933027+00:00'
[2025-05-12T21:11:22.740+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-12T21:11:22.753+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/x8/bvc5rcpd5t12mfz1khbckdsm0000gn/T
[2025-05-12T21:11:22.753+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd "/Users/moeinfahmide/Desktop/Job/Learning/Data Engineering/projects/youtube/youtube_dbt" && dbt run --profiles-dir "/Users/moeinfahmide/Desktop/Job/Learning/Data Engineering/projects/youtube" --models staging+ marts+']
[2025-05-12T21:11:22.760+0100] {subprocess.py:86} INFO - Output:
[2025-05-12T21:11:24.035+0100] {subprocess.py:93} INFO - [0m20:11:24  Running with dbt=1.9.4
[2025-05-12T21:11:24.038+0100] {subprocess.py:93} INFO - [0m20:11:24  Encountered an error:
[2025-05-12T21:11:24.038+0100] {subprocess.py:93} INFO - Runtime Error
[2025-05-12T21:11:24.039+0100] {subprocess.py:93} INFO -   Could not find profile named 'youtube_dbt'
[2025-05-12T21:11:24.671+0100] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-12T21:11:24.672+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-12T21:11:24.677+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-12T21:11:24.680+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=youtube_daily_pipeline, task_id=dbt_run, run_id=manual__2025-05-12T20:00:10.933027+00:00, execution_date=20250512T200010, start_date=20250512T201122, end_date=20250512T201124
[2025-05-12T21:11:24.684+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 4531)
[2025-05-12T21:11:24.725+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-05-12T21:11:24.736+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-12T21:11:24.738+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
