[2025-05-12T20:16:07.263+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-12T20:16:07.278+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_daily_pipeline.popular_ingest manual__2025-05-12T19:16:05.285947+00:00 [queued]>
[2025-05-12T20:16:07.280+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_daily_pipeline.popular_ingest manual__2025-05-12T19:16:05.285947+00:00 [queued]>
[2025-05-12T20:16:07.280+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-12T20:16:07.285+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): popular_ingest> on 2025-05-12 19:16:05.285947+00:00
[2025-05-12T20:16:07.291+0100] {logging_mixin.py:188} WARNING - /Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=99563) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-12T20:16:07.290+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_daily_pipeline', 'popular_ingest', 'manual__2025-05-12T19:16:05.285947+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/var/folders/x8/bvc5rcpd5t12mfz1khbckdsm0000gn/T/tmpyq4psh25']
[2025-05-12T20:16:07.291+0100] {standard_task_runner.py:64} INFO - Started process 99565 to run task
[2025-05-12T20:16:07.291+0100] {standard_task_runner.py:91} INFO - Job 9: Subtask popular_ingest
[2025-05-12T20:16:07.309+0100] {task_command.py:426} INFO - Running <TaskInstance: youtube_daily_pipeline.popular_ingest manual__2025-05-12T19:16:05.285947+00:00 [running]> on host macbookair.lan
[2025-05-12T20:16:07.436+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='youtube_daily_pipeline' AIRFLOW_CTX_TASK_ID='popular_ingest' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T19:16:05.285947+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T19:16:05.285947+00:00'
[2025-05-12T20:16:07.436+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-12T20:16:07.446+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/x8/bvc5rcpd5t12mfz1khbckdsm0000gn/T
[2025-05-12T20:16:07.447+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /Users/moeinfahmide/Desktop/Job/Learning/Data Engineering/projects/youtube && python ingestion/popular_ingest.py']
[2025-05-12T20:16:07.451+0100] {subprocess.py:86} INFO - Output:
[2025-05-12T20:16:07.454+0100] {subprocess.py:93} INFO - /bin/bash: line 0: cd: /Users/moeinfahmide/Desktop/Job/Learning/Data: No such file or directory
[2025-05-12T20:16:07.454+0100] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-12T20:16:07.455+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-12T20:16:07.458+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-12T20:16:07.461+0100] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=youtube_daily_pipeline, task_id=popular_ingest, run_id=manual__2025-05-12T19:16:05.285947+00:00, execution_date=20250512T191605, start_date=20250512T191607, end_date=20250512T191607
[2025-05-12T20:16:07.465+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task popular_ingest (Bash command failed. The command returned a non-zero exit code 1.; 99565)
[2025-05-12T20:16:07.470+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-05-12T20:16:07.479+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-12T20:16:07.479+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
