[2025-05-12T21:04:59.134+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-12T21:04:59.149+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T19:59:51.596061+00:00 [queued]>
[2025-05-12T21:04:59.152+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T19:59:51.596061+00:00 [queued]>
[2025-05-12T21:04:59.152+0100] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-12T21:04:59.157+0100] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2025-05-12 19:59:51.596061+00:00
[2025-05-12T21:04:59.162+0100] {logging_mixin.py:188} WARNING - /Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4262) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-12T21:04:59.163+0100] {standard_task_runner.py:64} INFO - Started process 4264 to run task
[2025-05-12T21:04:59.162+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'youtube_daily_pipeline', 'dbt_run', 'manual__2025-05-12T19:59:51.596061+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/youtube_pipeline.py', '--cfg-path', '/var/folders/x8/bvc5rcpd5t12mfz1khbckdsm0000gn/T/tmpz4mn23n6']
[2025-05-12T21:04:59.164+0100] {standard_task_runner.py:91} INFO - Job 24: Subtask dbt_run
[2025-05-12T21:04:59.182+0100] {task_command.py:426} INFO - Running <TaskInstance: youtube_daily_pipeline.dbt_run manual__2025-05-12T19:59:51.596061+00:00 [running]> on host macbookair.lan
[2025-05-12T21:04:59.474+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='youtube_daily_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T19:59:51.596061+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-12T19:59:51.596061+00:00'
[2025-05-12T21:04:59.474+0100] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-12T21:04:59.483+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/x8/bvc5rcpd5t12mfz1khbckdsm0000gn/T
[2025-05-12T21:04:59.484+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd "/Users/moeinfahmide/Desktop/Job/Learning/Data Engineering/projects/youtube/youtube_dbt" && dbt run --profiles-dir "/Users/moeinfahmide/Desktop/Job/Learning/Data Engineering/projects/youtube" --models staging+ marts+']
[2025-05-12T21:04:59.488+0100] {subprocess.py:86} INFO - Output:
[2025-05-12T21:05:00.607+0100] {subprocess.py:93} INFO - [0m20:05:00  Running with dbt=1.9.4
[2025-05-12T21:05:00.610+0100] {subprocess.py:93} INFO - [0m20:05:00  Encountered an error:
[2025-05-12T21:05:00.610+0100] {subprocess.py:93} INFO - Runtime Error
[2025-05-12T21:05:00.610+0100] {subprocess.py:93} INFO -   Could not find profile named 'youtube_dbt'
[2025-05-12T21:05:01.237+0100] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-12T21:05:01.239+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-12T21:05:01.247+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moeinfahmide/miniconda3/envs/open-air/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-12T21:05:01.251+0100] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=youtube_daily_pipeline, task_id=dbt_run, run_id=manual__2025-05-12T19:59:51.596061+00:00, execution_date=20250512T195951, start_date=20250512T200459, end_date=20250512T200501
[2025-05-12T21:05:01.257+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 24 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 4264)
[2025-05-12T21:05:01.265+0100] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-05-12T21:05:01.276+0100] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-12T21:05:01.278+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
